package dev

import (
	"bufio"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"strings"
	"time"

	"github.com/nwiley/arc/internal/agent"
	"github.com/nwiley/arc/internal/arc"
	"github.com/nwiley/arc/internal/prompt"
	"github.com/nwiley/arc/internal/resources"
)

// ClarifyOptions configures the clarification loop.
type ClarifyOptions struct {
	Discovery   *DiscoveryResult
	Complexity  TaskComplexity
	MaxRounds   int // default 3 (initial + 2 follow-ups)
	Model       string
	CommandName string
	Stdin       io.Reader
	Stdout      io.Writer
}

// ShouldAskQuestions returns true when the task complexity is medium or complex
// and the discovery agent produced at least one question.
func ShouldAskQuestions(complexity TaskComplexity, questions []string) bool {
	if complexity == ComplexitySimple {
		return false
	}
	return len(questions) > 0
}

// FormatDiscoverySummary formats a discovery result as a readable summary block.
func FormatDiscoverySummary(d *DiscoveryResult) string {
	var b strings.Builder

	b.WriteString("[dev] Task Summary\n")
	b.WriteString("  ")
	b.WriteString(d.TaskSummary)
	b.WriteString("\n\n")

	b.WriteString("  Complexity:  ")
	b.WriteString(string(d.Complexity))
	if d.WorkflowType != "" {
		b.WriteString(" (")
		b.WriteString(d.WorkflowType)
		b.WriteString(" workflow)")
	}
	b.WriteString("\n")

	if d.Approach != "" {
		b.WriteString("  Approach:    ")
		b.WriteString(d.Approach)
		b.WriteString("\n")
	}

	if len(d.SuggestedPhases) > 0 {
		names := make([]string, len(d.SuggestedPhases))
		for i, p := range d.SuggestedPhases {
			names[i] = p.Name
		}
		b.WriteString("  Phases:      ")
		b.WriteString(strings.Join(names, ", "))
		b.WriteString("\n")
	}

	return b.String()
}

// AskQuestions presents each question to the user and reads one line of input
// per question. Empty answers are recorded as-is (user pressed enter to skip).
func AskQuestions(questions []string, r io.Reader, w io.Writer) ([]Clarification, error) {
	scanner := bufio.NewScanner(r)
	clarifications := make([]Clarification, 0, len(questions))

	for i, q := range questions {
		fmt.Fprintf(w, "  %d. %s\n  > ", i+1, q)
		if !scanner.Scan() {
			if err := scanner.Err(); err != nil {
				return nil, fmt.Errorf("reading answer for question %d: %w", i+1, err)
			}
			// EOF — record remaining questions with empty answers
			clarifications = append(clarifications, Clarification{
				Question: q,
				Answer:   "",
			})
			for _, remaining := range questions[i+1:] {
				clarifications = append(clarifications, Clarification{
					Question: remaining,
					Answer:   "",
				})
			}
			return clarifications, nil
		}
		clarifications = append(clarifications, Clarification{
			Question: q,
			Answer:   strings.TrimSpace(scanner.Text()),
		})
	}

	return clarifications, nil
}

// RunClarificationLoop runs up to MaxRounds of question-answer rounds.
// Round 0 uses the discovery questions. Subsequent rounds use follow-up
// questions generated by a follow-up evaluation agent. The loop exits early
// if the follow-up agent returns no questions or errors.
func RunClarificationLoop(ctx context.Context, opts ClarifyOptions) ([]Clarification, arc.Usage, error) {
	if !ShouldAskQuestions(opts.Complexity, opts.Discovery.Questions) {
		return nil, arc.Usage{}, nil
	}

	maxRounds := opts.MaxRounds
	if maxRounds <= 0 {
		maxRounds = 3
	}

	fmt.Fprint(opts.Stdout, FormatDiscoverySummary(opts.Discovery))

	var allClarifications []Clarification
	var totalUsage arc.Usage
	questions := opts.Discovery.Questions

	for round := 0; round < maxRounds; round++ {
		if len(questions) == 0 {
			break
		}

		if round == 0 {
			fmt.Fprintln(opts.Stdout, "\n[dev] The following questions need your input:")
		} else {
			fmt.Fprintln(opts.Stdout, "\n[dev] Follow-up questions:")
		}

		roundClarifications, err := AskQuestions(questions, opts.Stdin, opts.Stdout)
		if err != nil {
			return allClarifications, totalUsage, err
		}
		allClarifications = append(allClarifications, roundClarifications...)

		// Don't evaluate follow-ups after the last allowed round.
		if round >= maxRounds-1 {
			break
		}

		fmt.Fprintln(opts.Stdout, "\n[dev] Evaluating answers...")

		followUpQuestions, usage, err := runFollowUp(ctx, opts, allClarifications)
		totalUsage = totalUsage.Add(usage)
		if err != nil {
			// Follow-up failure is non-fatal — proceed with what we have.
			break
		}
		if len(followUpQuestions) == 0 {
			break
		}

		questions = followUpQuestions
	}

	fmt.Fprintln(opts.Stdout)
	return allClarifications, totalUsage, nil
}

// runFollowUp spawns a follow-up evaluation agent that reviews the Q&A context
// and decides whether additional questions are needed.
func runFollowUp(ctx context.Context, opts ClarifyOptions, clarifications []Clarification) ([]string, arc.Usage, error) {
	tmplBytes, err := resources.PromptBytes("dev/followup.md")
	if err != nil {
		return nil, arc.Usage{}, fmt.Errorf("loading followup template: %w", err)
	}

	discoveryJSON, err := json.Marshal(opts.Discovery)
	if err != nil {
		return nil, arc.Usage{}, fmt.Errorf("marshaling discovery: %w", err)
	}

	clarificationsJSON, err := json.Marshal(clarifications)
	if err != nil {
		return nil, arc.Usage{}, fmt.Errorf("marshaling clarifications: %w", err)
	}

	rendered, err := prompt.RenderString(string(tmplBytes), prompt.TemplateContext{
		Params: map[string]string{
			"discovery_json":      string(discoveryJSON),
			"clarifications_json": string(clarificationsJSON),
		},
	})
	if err != nil {
		return nil, arc.Usage{}, fmt.Errorf("rendering followup template: %w", err)
	}

	spawnResult, err := agent.Spawn(ctx, agent.SpawnOptions{
		Prompt:       rendered,
		AllowedTools: []string{"Read"},
		MaxTurns:     1,
		Timeout:      60 * time.Second,
		Model:        opts.Model,
		CommandName:  opts.CommandName,
	})
	if err != nil {
		return nil, arc.Usage{}, err
	}

	questions, err := ParseFollowUpOutput(spawnResult.Output)
	if err != nil {
		return nil, spawnResult.Usage, err
	}

	return questions, spawnResult.Usage, nil
}

// ParseFollowUpOutput extracts follow-up questions from the agent's JSON output.
// Returns an empty slice if the questions array is empty (meaning no follow-ups needed).
func ParseFollowUpOutput(output string) ([]string, error) {
	lines := strings.Split(output, "\n")

	var jsonLines []string
	inBlock := false
	found := false

	for _, line := range lines {
		trimmed := strings.TrimSpace(line)

		if inBlock {
			if trimmed == "```" {
				found = true
				break
			}
			jsonLines = append(jsonLines, line)
		} else if strings.HasPrefix(trimmed, "```") {
			rest := strings.TrimSpace(trimmed[3:])
			if strings.EqualFold(rest, "json") {
				inBlock = true
				jsonLines = nil
			}
		}
	}

	if !found {
		return nil, fmt.Errorf("no JSON block found in follow-up output")
	}

	jsonStr := strings.Join(jsonLines, "\n")

	var raw struct {
		Questions []string `json:"questions"`
		Reasoning string   `json:"reasoning"`
	}

	if err := json.Unmarshal([]byte(jsonStr), &raw); err != nil {
		return nil, fmt.Errorf("failed to unmarshal follow-up output: %w", err)
	}

	if raw.Questions == nil {
		raw.Questions = []string{}
	}

	return raw.Questions, nil
}
